version: 2.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-yarn
          command: "sudo npm install -g yarn@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
      - run:
          name: install-yarn-wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
