version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run:
          name: install-yarn
          command: yarn install
      - run:
          name: test
          command: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage
